[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "winfox"
version = "0.5.0"
description = "Winfox Python package with winfox.rdp as the primary automation framework"
authors = ["daijro <daijro.dev@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = [
    "client",
    "fingerprint",
    "browser",
    "scraping",
    "injector",
    "firefox",
    "rdp",
    "winfox",
]
classifiers = [
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Browsers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
packages = [
    { include = "winfox" },
]

[tool.poetry.dependencies]
python = "^3.10"
rich-click = "*"
rich = "*"
platformdirs = "*"
geckordp = "*"
websockets = "*"

[tool.poetry.scripts]
winfox = "winfox.__main__:cli"
